// src/App.jsx
import React, { useState, useEffect } from 'react';
import Auth from './components/Auth';
import TaskManager from './components/TaskManager';
import About from './components/About';
import Toast from './components/Toast';
import { login as loginApi, register as registerApi } from './services/taskApi';

function App() {
    const [isAuthenticated, setIsAuthenticated] = useState(false);
    const [currentPage, setCurrentPage] = useState('home');
    const [currentUser, setCurrentUser] = useState({
        id: null,
        name: '',
        email: ''
    });
    const [toast, setToast] = useState(null);

    useEffect(() => {
        const savedUser = localStorage.getItem('user');
        if (savedUser) {
            setCurrentUser(JSON.parse(savedUser));
            setIsAuthenticated(true);
        }
    }, []);

    const showToast = (message, type = 'info') => {
        console.log('showToast called:', { message, type });
        setToast({ message, type });
        console.log('toast state set');
    };

    const handleLogin = async (credentials) => {
        try {
            const user = await loginApi(credentials);
            setCurrentUser(user);
            setIsAuthenticated(true);
            setCurrentPage('home');
            localStorage.setItem('user', JSON.stringify(user));
            showToast(`Добро пожаловать, ${user.name || user.email}!`, 'success');
        } catch (error) {
            console.log('Login error:', error);
            console.log('Error message:', error.message);
            showToast(error.message || 'Произошла ошибка', 'error');
        }
    };

    const handleRegister = async (data) => {
        try {
            const user = await registerApi(data);
            setCurrentUser(user);
            setIsAuthenticated(true);
            setCurrentPage('home');
            localStorage.setItem('user', JSON.stringify(user));
            showToast(`Регистрация успешна! Добро пожаловать, ${user.name}!`, 'success');
        } catch (error) {
            showToast(error.message, 'error');
        }
    };

    const handleLogout = () => {
        setIsAuthenticated(false);
        setCurrentPage('home');
        setCurrentUser({ id: null, name: '', email: '' });
        localStorage.removeItem('user');
    };

    if (!isAuthenticated) {
        return (
            <>
                <Auth onLogin={handleLogin} onRegister={handleRegister} />
                {toast && (
                    <Toast
                        message={toast.message}
                        type={toast.type}
                        onClose={() => setToast(null)}
                    />
                )}
            </>
        );
    }

    return (
        <div id="app">
            <nav className="navbar navbar-expand-lg navbar-dark bg-gradient-primary shadow-sm sticky-top">
                <div className="container-fluid px-4">
                    <a className="navbar-brand fw-bold fs-4" href="#">✓ Task Manager</a>

                    <button className="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav">
                        <span className="navbar-toggler-icon"></span>
                    </button>

                    <div className="collapse navbar-collapse" id="navbarNav">
                        <ul className="navbar-nav mx-auto">
                            <li className="nav-item">
                                <a
                                    className={`nav-link ${currentPage === 'home' ? 'active' : ''}`}
                                    onClick={(e) => { e.preventDefault(); setCurrentPage('home'); }}
                                    href="#"
                                >
                                    📋 Задачи
                                </a>
                            </li>
                            <li className="nav-item">
                                <a
                                    className={`nav-link ${currentPage === 'about' ? 'active' : ''}`}
                                    onClick={(e) => { e.preventDefault(); setCurrentPage('about'); }}
                                    href="#"
                                >
                                    ℹ️ О нас
                                </a>
                            </li>
                        </ul>

                        <div className="d-flex align-items-center gap-3">
                            <span className="text-white">{currentUser.name || currentUser.email}</span>
                            <button onClick={handleLogout} className="btn btn-outline-light btn-sm">
                                Выход
                            </button>
                        </div>
                    </div>
                </div>
            </nav>

            <main className="container py-4">
                {currentPage === 'home' && <TaskManager userId={currentUser.id} showToast={showToast} />}
                {currentPage === 'about' && <About />}
            </main>

            {toast && (
                <Toast
                    message={toast.message}
                    type={toast.type}
                    onClose={() => setToast(null)}
                />
            )}
        </div>
    );
}

export default App;

// src/App.vue
<template>
  <div id="app">
    <template v-if="!isAuthenticated">
      <Auth @login="handleLogin" @register="handleRegister" />
    </template>
    <template v-else>
      <nav class="navbar navbar-expand-lg navbar-dark bg-gradient-primary shadow-sm sticky-top">
        <div class="container-fluid px-4">
          <a class="navbar-brand fw-bold fs-4" href="#">✓ Task Manager</a>

          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav mx-auto">
              <li class="nav-item">
                <a
                  class="nav-link"
                  :class="{ active: currentPage === 'home' }"
                  @click="currentPage = 'home'"
                  href="#"
                >
                  📋 Задачи
                </a>
              </li>
              <li class="nav-item">
                <a
                  class="nav-link"
                  :class="{ active: currentPage === 'about' }"
                  @click="currentPage = 'about'"
                  href="#"
                >
                  ℹ️ О нас
                </a>
              </li>
            </ul>

            <div class="d-flex align-items-center gap-3">
              <span class="text-white">{{ currentUser.name || currentUser.email }}</span>
              <button @click="handleLogout" class="btn btn-outline-light btn-sm">
                Выход
              </button>
            </div>
          </div>
        </div>
      </nav>

      <main class="container py-4">
        <TaskManager v-if="currentPage === 'home'" :userId="currentUser.email" />
        <About v-else-if="currentPage === 'about'" />
      </main>
    </template>
  </div>
</template>

<script setup>
import { ref } from 'vue'
import Auth from './components/Auth.vue'
import TaskManager from './components/TaskManager.vue'
import About from './components/About.vue'

const isAuthenticated = ref(false)
const currentPage = ref('home')
const currentUser = ref({
  name: '',
  email: ''
})

const handleLogin = (credentials) => {
  currentUser.value = {
    name: credentials.email.split('@')[0],
    email: credentials.email
  }
  isAuthenticated.value = true
  currentPage.value = 'home'
  localStorage.setItem('user', JSON.stringify(currentUser.value))
}

const handleRegister = (data) => {
  currentUser.value = {
    name: data.name,
    email: data.email
  }
  isAuthenticated.value = true
  currentPage.value = 'home'
  localStorage.setItem('user', JSON.stringify(currentUser.value))
}

const handleLogout = () => {
  isAuthenticated.value = false
  currentPage.value = 'home'
  currentUser.value = {
    name: '',
    email: ''
  }
  localStorage.removeItem('user')
}

// Проверяем наличие сохраненной сессии при загрузке
const savedUser = localStorage.getItem('user')
if (savedUser) {
  currentUser.value = JSON.parse(savedUser)
  isAuthenticated.value = true
}
</script>

<style scoped>
/* Минимальные стили для Bootstrap */
</style>
